[package]
name = "debug_unsafe"
version = "0.1.2"
authors = ["Dmitry Rodionov <gh@rdmtr.com>"]
description = "For tests to trigger panic instead of UB in unsafe calls"
documentation = "https://docs.rs/debug_unsafe/"
repository = "https://github.com/RoDmitry/debug_unsafe"
categories = ["development-tools::debugging", "rust-patterns", "no-std"]
keywords = ["debug", "unsafe", "unchecked", "unwrap", "arraystring"]
include = ["src"]
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2021"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
name = "debug_unsafe"
path = "src/lib.rs"

[dependencies]
arraystring = { version = "0.3", optional = true }

[features]
arraystring = ["dep:arraystring"]
